### ISSUE TITLE
[Compat] ItemZoom in wrong place when hovering in CustomNPCs trader screen

### ISSUE THREAD

**Issue by thephoenixlodge** [mezz/ItemZoom#7]
http://imgur.com/a/A98cK

Only items in the 'what the trader wants' bit render over the inventory like this. Items the trader is selling, as well as the items in the player inventory render the item zoom in the correct place while in this GUI.

**Comment by mezz** [comment]
Thanks for the report!
Please report this to CustomNPCs:
It looks like CustomNPCs uses an OpenGL transform during its tooltip rendering in this one case, which offsets the tooltip to the right location but also offsets ItemZoom which uses the tooltip event. I think this is the case because ItemZoom seems to be offset from its normal position on the screen about the same amount that the tooltip is offset from the top-left corner. I assume this would also affect other mods which use this event to render, like AppleSkin.
